name: codestyle

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    name: codestyle-check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.0.0
      - name: Run codestyle-check
        run: bin/codestyle-check

  analyze:
    name: codestyle-analyze
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.0.0
      - name: Run codestyle-analyze
        run: bin/codestyle-analyze
